import React, { Component } from 'react';
import Head from 'next/head';
import GottaGoPicture from './GottaGoPicture';
import DogAppPicture from './DogAppPicture';
import GetMoneyPicture from './GetMoneyPicture';

export default class Projects extends Component {
  render() {
    return (
      <div className="projects">
        <Head>
          <title>Cole Berman</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="picture" id="gotta-go-picture">
          <GottaGoPicture />
        </div>
        <div className="picture" id="dog-app-picture">
          <DogAppPicture />
        </div>
        <div className="picture" id="get-money-app-picture">
          <GetMoneyPicture />
        </div>

        <main className="projects-main">
          <div id="aboutMe">
            <h1 className="pageTitle"></h1>
            <p className="infoText"></p>
          </div>
        </main>

        <footer className="projects-footer"></footer>
      </div>
    );
  }
}
